name: '💬 Ask Question'
description: Make queries about the project
labels: ['? Type Question']
body:
  - type: markdown
    attributes:
      value: |
        **Please search for similar issues regarding your concerns before opening a new issue.**

  - type: input
    id: question
    attributes:
      label: Question
      placeholder: Ask us a question about the project
    validations:
      required: true
