name: '💬 Question'
description: Ask us about the project
labels: ['? Type Question']
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Please search for similar issues before opening a new issue

  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Ask us a question about the project
