name: ðŸ› Bug Report
description: Report unexpected behavior
labels: ['â—‹ Type Bug']
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Please search for similar issues before opening a new issue

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Tell us what's actually happening vs. what's intended/expected. Include steps to reproduce the issue. It may help to add screenshots!
      placeholder: |
        The app keeps crashing when I navigate through my bookmarks.

        1) Open app
        2) Click on bookmarks icon
        3) Navigate to Nitnem
        4) Navigate back

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Versions of platform, device, OS, browser, etc.
      placeholder: v1.2.4, iPhone 13 Pro Max, iOS 15.2
