name: ✅ Task
description: For team use only
labels: ['✓ Type Task']
body:
  - type: markdown
    attributes:
      value: '## For team use only'

  - type: markdown
    attributes:
      value: |
        @Team please use for technical work.

  - type: textarea
    id: summary
    attributes:
      label: Summary

  - type: textarea
    id: approach
    attributes:
      label: Approach
      description: 'Please list actions and sub-tasks here'
      value: '- '
