name: ✅ Task
description: For team use only
labels: ['✓ Type Task']
body:
  - type: markdown
    value: '## For team use only'

  - type: markdown
    attributes:
      value: |
        @Team please use for technical work.

  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Approach
      description: 'Please list actions and sub-tasks here'
      value: |
        -
