name: 🧐 Spike
description: For team use only
labels: ['⧬ Type Spike']
body:
  - type: markdown
    attributes:
      value: '## For team use only'

  - type: markdown
    attributes:
      value: |
        @Team please use for knowledge exploration.

  - type: textarea
    id: investigation
    attributes:
      label: Investigation
      placeholder: Please outline requirements and ideas here

  - type: input
    id: timebox
    attributes:
      label: Timebox

  - type: textarea
    id: tasks
    attributes:
      label: Outcome
      description: 'Please list criteria for completion'
      value: '- '
