name: ⧬ Spike
description: For team use only
labels: ['⧬ Type Spike']
body:
  - type: markdown
    attributes:
      value: |
        **For team use only.** @Team please use for knowledge exploration.

  - type: textarea
    id: investigation
    attributes:
      label: Investigation
      placeholder: Please outline requirements and ideas here
    validations:
      required: true

  - type: input
    id: timebox
    attributes:
      label: Timebox
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Outcome
      description: 'Please list criteria for completion'
      value: |
        -
    validations:
      required: true
