name: ⚡️ Epic
description: For team use only
labels: ['ϟ Type Epic']
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > For team use only
        > For defining a high-level initiative / goal on the roadmap

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Reason for Epic
      placeholder: |
        On mobile, we'd like to decouple deployment from feature release for a number of reasons:

        - Control feature release rollout
        - We'd like to personalise the app for users with audience-targeted features
        - Personalised app based on time/events
        - A/B experiments
    validations:
      required: true

  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: High-level goals of Epic
      placeholder: We'd like to integrate a feature flagging service that will provide us with a UI that we can toggle, audience segmentation, A/B tests, and any other goodies.
    validations:
      required: true

