--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "Chat with the team and community on Slack"
    name: Chat
    url: "https://chat.shabados.com"
  - 
    about: "See different ways to get in touch with the team"
    name: Support & Feedback
    url: "https://github.com/ShabadOS/.github/blob/master/SUPPORT.md"
